InvoicesManagmentApp/Models/Invoice.cs
using Microsoft.EntityFrameworkCore;

namespace InvoicesManagmentApp.Models
{
    public class Invoice
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Status { get; set; }
        public DateOnly? IssueDate { get; set; }
        public DateOnly? DueDate { get; set; }
        public List<InvoiceItem> InvoiceItems { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    }
}

InvoicesManagmentApp/Pages/Invoices/Create.cshtml.cs
using InvoicesManagmentApp.Models;
using InvoicesManagmentApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InvoicesManagmentApp.Pages.Invoices
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext context;

        [BindProperty]
        public InvoiceDto InvoiceDto { get; set; } = new();

        [BindProperty]
        public InvoiceItemDto InvoiceItemDto { get; set; } = new();


        public CreateModel(ApplicationDbContext context)
        {
            this.context = context;
        }

        public void OnGet()
        {
        }


        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var invoiceItem = new InvoiceItem
            {
                Service = InvoiceItemDto.Service,
                UnitPrice = InvoiceItemDto.UnitPrice,
                Quantity = InvoiceItemDto.Quantity,
            };

            var invoice = new Invoice
            {
                Number = InvoiceDto.Number,
                Status = InvoiceDto.Status,
                IssueDate = InvoiceDto.IssueDate,
                DueDate = InvoiceDto.DueDate,
                ClientName = InvoiceDto.ClientName,
                Email = InvoiceDto.Email,
                Phone = InvoiceDto.Phone,
                Address = InvoiceDto.Address,
                InvoiceItems = new List<InvoiceItem>() // Initialize the collection
            };

            invoice.InvoiceItems.Add(invoiceItem);

            context.Invoices.Add(invoice);
            context.SaveChanges();

            return RedirectToPage("/Invoices/Edit", new { id = invoice.Id });
        }
    }
}

InvoicesManagmentApp/Pages/Invoices/Delete.cshtml.cs
using InvoicesManagmentApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InvoicesManagmentApp.Pages.Invoices
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext context;

        public DeleteModel(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult OnGet(int id)
        {
            var invoice = context.Invoices.Find(id);
            if (invoice != null)
            {
                context.Invoices.Remove(invoice);
                context.SaveChanges();
            }

            return RedirectToPage("/Invoices/Index");
        }
    }
}

InvoicesManagmentApp/Pages/Invoices/Edit.cshtml.cs
using InvoicesManagmentApp.Models;
using InvoicesManagmentApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace InvoicesManagmentApp.Pages.Invoices
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public InvoiceDto InvoiceDto { get; set; } = new InvoiceDto();

        [BindProperty]
        public InvoiceItemDto InvoiceItemDto { get; set; } = new();

        public Invoice Invoice { get; set; } = new();


        private readonly ApplicationDbContext context;

        public EditModel(ApplicationDbContext context)
        {
            this.context = context;
        }


        public IActionResult OnGet(int id)
        {
            var invoice = context.Invoices.Include(i => i.InvoiceItems).FirstOrDefault(i => i.Id == id);
            if (invoice == null)
            {
                return RedirectToPage("/Invoices/Index");
            }

            Invoice = invoice;

            InvoiceDto.Number = invoice.Number;
            InvoiceDto.Status = invoice.Status;
            InvoiceDto.IssueDate = invoice.IssueDate;
            InvoiceDto.DueDate = invoice.DueDate;

            InvoiceDto.ClientName = invoice.ClientName;
            InvoiceDto.Email = invoice.Email;
            InvoiceDto.Phone = invoice.Phone;
            InvoiceDto.Address = invoice.Address;

            return Page();
        }


        public string successMessage = "";

        public IActionResult OnPost(int id)
        {
            var invoice = context.Invoices.Include(i => i.InvoiceItems).FirstOrDefault(i => i.Id == id);
            if (invoice == null)
            {
                return RedirectToPage("/Invoices/Index");
            }

            Invoice = invoice;



            ModelState.Remove(nameof(InvoiceItemDto.Service));
            ModelState.Remove(nameof(InvoiceItemDto.Quantity));
            ModelState.Remove(nameof(InvoiceItemDto.UnitPrice));

            if (!ModelState.IsValid)
            {
                return Page();
            }


            invoice.Number = InvoiceDto.Number;
            invoice.Status = InvoiceDto.Status;
            invoice.IssueDate = InvoiceDto.IssueDate;
            invoice.DueDate = InvoiceDto.DueDate;

            invoice.ClientName = InvoiceDto.ClientName;
            invoice.Email = InvoiceDto.Email;
            invoice.Phone = InvoiceDto.Phone;
            invoice.Address = InvoiceDto.Address;

            context.SaveChanges();

            successMessage = "Invoice Updated Successfully!";

            return Page();
        }



        public IActionResult OnPostCreateItem(int id)
        {
            var invoice = context.Invoices.Include(i => i.InvoiceItems).FirstOrDefault(i => i.Id == id);
            if (invoice == null)
            {
                return RedirectToPage("/Invoices/Index");
            }

            if (string.IsNullOrEmpty(InvoiceItemDto.Service) || InvoiceItemDto.Quantity <= 0 || InvoiceItemDto.UnitPrice <= 0)
            {
                // submitted Item is not valid
                TempData["ErrorMessage"] = "Submitted Item is not valid!";
                return RedirectToPage("/Invoices/Edit", new { id });
            }

            var invoiceItem = new InvoiceItem
            {
                Service = InvoiceItemDto.Service,
                Quantity = InvoiceItemDto.Quantity,
                UnitPrice = InvoiceItemDto.UnitPrice,
            };

            invoice.InvoiceItems.Add(invoiceItem);
            context.SaveChanges();

            return RedirectToPage("/Invoices/Edit", new { id });
        }



        public IActionResult OnGetDeleteItem(int invoiceId, int itemId)
        {
            var item = context.InvoiceItems.Find(itemId);
            if (item != null)
            {
                context.InvoiceItems.Remove(item);
                context.SaveChanges();
            }

            return RedirectToPage("/Invoices/Edit", new { id = invoiceId });
        }
    }
}

InvoicesManagmentApp/Pages/Invoices/Index.cshtml.cs
using InvoicesManagmentApp.Models;
using InvoicesManagmentApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace InvoicesManagmentApp.Pages.Invoices
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext context;

        public List<Invoice> invoiceList = new();

        public IndexModel(ApplicationDbContext context)
        {
            this.context = context;
        }

        public void OnGet()
        {
            invoiceList = context.Invoices.Include(i => i.InvoiceItems).OrderByDescending(i => i.Id).ToList();
        }
    }
}

InvoicesManagmentApp/Pages/Invoices/Create.cshtml
@page
@model InvoicesManagmentApp.Pages.Invoices.CreateModel
@{
}

<h2 class="text-center mb-3">New Invoice</h2>

<form method="post">
    <div class="row g-2 mb-3">
        <div class="col-lg-6">

            <div class="card h-100">
                <div class="card-header">
                    Invoice Details
                </div>
                <div class="card-body">

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Invoice No</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Number">
                            <span asp-validation-for="InvoiceDto.Number" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Payment Status</label>
                        <div class="col-sm-8">
                            <select class="form-select" asp-for="InvoiceDto.Status">
                                <option value="Pending">Pending</option>
                                <option value="Paid">Paid</option>
                                <option value="Overdue">Overdue</option>
                            </select>
                            <span asp-validation-for="InvoiceDto.Status" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Issue Date</label>
                        <div class="col-sm-8">
                            <input class="form-control" type="date" asp-for="InvoiceDto.IssueDate">
                            <span asp-validation-for="InvoiceDto.IssueDate" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-4 col-form-label">Due Date</label>
                        <div class="col-sm-8">
                            <input class="form-control" type="date" asp-for="InvoiceDto.DueDate">
                            <span asp-validation-for="InvoiceDto.DueDate" class="text-danger"></span>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="col-lg-6">

            <div class="card h-100">
                <div class="card-header">
                    Client Details
                </div>
                <div class="card-body">

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Client</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.ClientName">
                            <span asp-validation-for="InvoiceDto.ClientName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Email</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Email">
                            <span asp-validation-for="InvoiceDto.Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Phone</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Phone">
                            <span asp-validation-for="InvoiceDto.Phone" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-4 col-form-label">Address</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Address">
                            <span asp-validation-for="InvoiceDto.Address" class="text-danger"></span>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="card mb-3">
        <div class="card-header">
            Service Details
        </div>
        <div class="card-body">

            <div class="row g-2">
                <div class="col-lg-6">
                    <label class="form-label">Service</label>
                    <input class="form-control" asp-for="InvoiceItemDto.Service">
                    <span asp-validation-for="InvoiceItemDto.Service" class="text-danger"></span>
                </div>

                <div class="col-lg-2 col-sm-4">
                    <label class="form-label">Quantity</label>
                    <input class="form-control" asp-for="InvoiceItemDto.Quantity" id="quatityInput" oninput="updateTotalPrice()">
                    <span asp-validation-for="InvoiceItemDto.Quantity" class="text-danger"></span>
                </div>

                <div class="col-lg-2 col-sm-4">
                    <label class="form-label">Unit Price</label>
                    <input class="form-control" asp-for="InvoiceItemDto.UnitPrice" id="unitPriceInput" oninput="updateTotalPrice()">
                    <span asp-validation-for="InvoiceItemDto.UnitPrice" class="text-danger"></span>
                </div>

                <div class="col-lg-2 col-sm-4">
                    <label class="form-label">Total Price</label>
                    <input class="form-control" disabled id="totalPriceInput">
                </div>
            </div>

        </div>
    </div>


    <button type="submit" class="btn btn-primary me-2">Submit</button>
    <a class="btn btn-outline-primary" asp-page="/Invoices/Index" role="button">Cancel</a>

</form>



<script>
    function updateTotalPrice() {

        let quantity = document.getElementById("quatityInput").value;
        let unitPrice = document.getElementById("unitPriceInput").value;

        if (isNaN(quantity) || isNaN(unitPrice)) {
            document.getElementById("totalPriceInput").value = "0";
        }
        else {
            let totalPrice = quantity * unitPrice;
            document.getElementById("totalPriceInput").value = totalPrice;
        }
    }


    updateTotalPrice();
</script>

InvoicesManagmentApp/Pages/Invoices/Delete.cshtml
@page
@model InvoicesManagmentApp.Pages.Invoices.DeleteModel
@{
}

InvoicesManagmentApp/Pages/Invoices/Edit.cshtml
@page
@model InvoicesManagmentApp.Pages.Invoices.EditModel
@{
    var errorMessage = TempData["ErrorMessage"]?.ToString();
}


<h2 class="text-center mb-3">Edit Invoice</h2>


@if (Model.successMessage.Length > 0)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@Model.successMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else if (errorMessage != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@errorMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form method="post">
    <div class="row g-2 mb-3">
        <div class="col-lg-6">

            <div class="card h-100">
                <div class="card-header">
                    Invoice Details
                </div>
                <div class="card-body">

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Invoice Id</label>
                        <div class="col-sm-8">
                            <input class="form-control-plaintext" readonly value="@Model.Invoice.Id">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Invoice No</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Number">
                            <span asp-validation-for="InvoiceDto.Number" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Payment Status</label>
                        <div class="col-sm-8">
                            <select class="form-select" asp-for="InvoiceDto.Status">
                                <option value="Pending">Pending</option>
                                <option value="Paid">Paid</option>
                                <option value="Overdue">Overdue</option>
                            </select>
                            <span asp-validation-for="InvoiceDto.Status" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Issue Date</label>
                        <div class="col-sm-8">
                            <input class="form-control" type="date" asp-for="InvoiceDto.IssueDate">
                            <span asp-validation-for="InvoiceDto.IssueDate" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-4 col-form-label">Due Date</label>
                        <div class="col-sm-8">
                            <input class="form-control" type="date" asp-for="InvoiceDto.DueDate">
                            <span asp-validation-for="InvoiceDto.DueDate" class="text-danger"></span>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="col-lg-6">

            <div class="card h-100">
                <div class="card-header">
                    Client Details
                </div>
                <div class="card-body">

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Client</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.ClientName">
                            <span asp-validation-for="InvoiceDto.ClientName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Email</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Email">
                            <span asp-validation-for="InvoiceDto.Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-sm-4 col-form-label">Phone</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Phone">
                            <span asp-validation-for="InvoiceDto.Phone" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-4 col-form-label">Address</label>
                        <div class="col-sm-8">
                            <input class="form-control" asp-for="InvoiceDto.Address">
                            <span asp-validation-for="InvoiceDto.Address" class="text-danger"></span>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="card mb-3">
        <div class="card-header">
            Service Details
        </div>
        <div class="card-body">

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addServiceModal">
                Add Service
            </button>

            <table class="table">
                <thead>
                    <tr>
                        <th>Service</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>

                    @{
                        decimal totalPrice = 0;
                        foreach (var item in Model.Invoice.InvoiceItems)
                        {
                            totalPrice += item.Quantity * item.UnitPrice;

                            <tr>
                                <td>@item.Service</td>
                                <td>@item.Quantity</td>
                                <td>@(item.UnitPrice)$</td>
                                <td>@(item.Quantity * item.UnitPrice)$</td>
                                <td style="white-space:nowrap">
                                    <a class="btn btn-danger btn-sm" asp-page="/Invoices/Edit" asp-page-handler="DeleteItem"
                                       asp-route-invoiceId="@Model.Invoice.Id" asp-route-itemId="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
                <tfoot class="table-group-divider">
                    <tr class="table-light">
                        <td></td>
                        <td></td>
                        <td class="text-end fw-bold">Total</td>
                        <td>@(totalPrice)$</td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>


        </div>
    </div>


    <button type="submit" class="btn btn-primary me-2">Submit</button>
    <a class="btn btn-outline-primary" asp-page="/Invoices/Index" role="button">Cancel</a>

</form>




<!-- Modal -->
<div class="modal fade" id="addServiceModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Add Service</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">


                <form method="post" asp-page-handler="CreateItem" asp-route-id="@Model.Invoice.Id">
                    <div class="mb-3">
                        <label class="form-label">Service</label>
                        <input class="form-control" asp-for="InvoiceItemDto.Service">
                        <span asp-validation-for="InvoiceItemDto.Service" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Quantity</label>
                        <input class="form-control" asp-for="InvoiceItemDto.Quantity" id="quatityInput" oninput="updateTotalPrice()">
                        <span asp-validation-for="InvoiceItemDto.Quantity" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Unit Price</label>
                        <input class="form-control" asp-for="InvoiceItemDto.UnitPrice" id="unitPriceInput" oninput="updateTotalPrice()">
                        <span asp-validation-for="InvoiceItemDto.UnitPrice" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Total Price</label>
                        <input class="form-control" disabled id="totalPriceInput">
                    </div>


                    <button type="submit" class="btn btn-primary">Submit</button>

                </form>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>





<script>
    function updateTotalPrice() {

        let quantity = document.getElementById("quatityInput").value;
        let unitPrice = document.getElementById("unitPriceInput").value;

        if (isNaN(quantity) || isNaN(unitPrice)) {
            document.getElementById("totalPriceInput").value = "0";
        }
        else {
            let totalPrice = quantity * unitPrice;
            document.getElementById("totalPriceInput").value = totalPrice;
        }
    }


    updateTotalPrice();
</script>

InvoicesManagmentApp/Pages/Invoices/Index.cshtml
@page
@model InvoicesManagmentApp.Pages.Invoices.IndexModel
@{
}

<h2 class="text-center">Invoices</h2>
<a class="btn btn-primary mb-1" asp-page="/Invoices/Create">New Invoice</a>

<table class="table" id="idListInvoices">
    <thead>
        <tr>
            <th>ID</th>
            <th>Invoice No</th>
            <th>Status</th>
            <th>Client</th>
            <th>Total Price</th>
            <th>Issue Date</th>
            <th>Due Date</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody class="table-group-divider">
        @foreach (var invoice in Model.invoiceList)
        {
            decimal totalPrice = 0;
            foreach (var item in invoice.InvoiceItems)
            {
                totalPrice += item.Quantity * item.UnitPrice;
            }

            <tr>
                <td>@invoice.Id</td>
                <td>@invoice.Number</td>
                <td>
                    @if (invoice.Status == "Pending")
                    {
                        <span class="badge bg-warning text-white">@invoice.Status</span>
                    }
                    else if (invoice.Status == "Paid")
                    {
                        <span class="badge bg-success text-white">@invoice.Status</span>
                    }
                    else if (invoice.Status == "Overdue")
                    {
                        <span class="badge bg-danger text-white">@invoice.Status</span>
                    }
                    else
                    {
                        <span class="badge text-bg-dark">@invoice.Status</span>
                    }
                </td>
                <td>@invoice.ClientName</td>
                <td>@(totalPrice)$</td>
                <td>@invoice.IssueDate</td>
                <td>@invoice.DueDate</td>
                <td style="white-space:nowrap">
                    <a class="btn btn-primary btn-sm" asp-page="/Invoices/Edit" asp-route-id="@invoice.Id">
                        <i class="bi bi-pencil"></i>
                    </a>
                    <button class="btn btn-danger btn-sm" onclick="deleteInvoice(@invoice.Id)">
                        <i class="bi bi-trash"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>


<script>
    function deleteInvoice(id) {
        Swal.fire({
           title: 'Delete Invoice!',
           text: 'Do you want to delete this invoice with ID ' + id + '?',
           showCancelButton: true,
           confirmButtonText: "Yes, delete it!",
           confirmButtonColor: "#d33",
           cancelButtonText: "No, cancel!"
        }).then(function(result) {

          if (result.isConfirmed) {
            window.location.href = "/Invoices/Delete?id=" + id;
          }

        });
    }
</script>


@section Scripts {
    @* datatables must be added after jquery => either add to _Layout or add to Scripts section *@
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
    <script>
        new DataTable('#idListInvoices', {ordering:  false});
    </script>
}